Repository goorea/muscleman, pull requests merged in 2022-08, with the labels that each got.

#108 [feat] error-report
  .env.example
  android/app/build.gradle
  android/sentry.properties
  ios/Podfile.lock
  ios/muscleman.xcodeproj/project.pbxproj
  ios/sentry.properties
  mocks/index.ts
  package.json
  src/App.tsx
  src/types/env.d.ts
  yarn.lock
Labels: enhancement, test

#107 [fix] 소셜 로그인 유형에 따라 아이콘 변경되도록 수정
  src/fragments/user.ts
  src/screens/ProfileScreen/index.tsx
Labels: bug

#106 [feat] 소셜 로그인
  .env.example
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/kr/muscleman/MainApplication.java
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/settings.gradle
  ios/Podfile.lock
  ios/muscleman-Bridging-Header.h
  ios/muscleman.xcodeproj/project.pbxproj
  ios/muscleman.xcodeproj/xcshareddata/xcschemes/muscleman.xcscheme
  ios/muscleman/AppDelegate.m
  ios/muscleman/Info.plist
  mocks/index.ts
  package.json
  src/components/GoogleLogin/index.tsx
  src/components/KakaoLogin/index.tsx
  src/components/NaverLogin/index.tsx
  src/hooks/useSetRecoilStates.ts
  src/operations/mutations/socialLogin.ts
  src/screens/LoginScreen/index.tsx
  src/types/env.d.ts
  tests/TodayPlan.test.tsx
  yarn.lock
Labels: enhancement

#114 [feat] 애플 로그인
  ios/Podfile.lock
  ios/muscleman.xcodeproj/project.pbxproj
  ios/muscleman/Info.plist
  ios/muscleman/muscleman.entitlements
  mocks/index.ts
  package.json
  src/components/AppleLogin/index.tsx
  src/screens/LoginScreen/index.tsx
  yarn.lock
Labels: enhancement

#117 [fix] iOS Release 배포 설정 변경
  .env.example
  .gitignore
  android/app/build.gradle
  ios/muscleman.xcodeproj/project.pbxproj
  ios/muscleman.xcodeproj/xcshareddata/xcschemes/muscleman.xcscheme
  ios/muscleman/Info.plist
  package.json
Labels: bug
