Repository goorea/muscleman, pull requests merged in 2022-10, with the labels that each got.

#151 [Feat] 운동 계획 달력 하단 리스트에서 바로 운동 완료를 체크할 수 있는 기능
  src/components/Icon/index.tsx
  src/components/Plan/Plan.test.tsx
  src/components/Plan/index.tsx
  src/components/TodayPlan/hooks/useToggleComplete.ts
  src/screens/PlansScreen/index.tsx
  yarn.lock
Labels: enhancement

#153 [fix] 운동명이 길어질 때 UI가 잘리는 현상
  src/components/EditPlan/index.tsx
  src/components/EditPlan/styled.ts
  src/components/TodayPlan/__snapshots__/TodayPlan.test.tsx.snap
  src/components/TodayPlan/index.tsx
  src/components/TodayPlan/styled.ts
Labels: bug

#154 [fix] 로그인 하지 않은채로 운동 계획
  ios/Podfile.lock
  package.json
  src/components/NeedAuthenticate/NeedAuthenticate.test.tsx
  src/components/NeedAuthenticate/index.tsx
  src/components/NeedAuthenticate/styled.ts
  src/screens/PlansScreen/PlansScreen.test.tsx
  src/screens/PlansScreen/index.tsx
  src/screens/ProfileScreen/ProfileScreen.test.tsx
  src/screens/ProfileScreen/index.tsx
  src/screens/ProfileScreen/styled.ts
  yarn.lock
Labels: bug

#156 [fix] 로그아웃 후 로그인 했을 때 데이터 패치
  src/hooks/useSetRecoilStates.ts
Labels: merge needed

#155 [fix] 운동 설정 키패드 버그
  src/components/EditPlan/styled.ts
  src/screens/EditPlanScreen/hooks/useIsEditing.ts
  src/screens/EditPlanScreen/hooks/useReset.ts
  src/screens/EditPlanScreen/index.tsx
  src/screens/EditPlanScreen/styled.ts
Labels: merge needed
